general.import = [
	""
]

cursor.style.shape = "Underline"

font.size = 12.0

font.bold.family = "Maple Mono NF CN"
font.bold.style = "Bold"

font.bold_italic.family = "Maple Mono NF CN"
font.bold_italic.style = "BoldItalic"

font.italic.family = "Maple Mono NF CN"
font.italic.style = "Italic"

font.normal.family = "Maple Mono NF CN"
font.normal.style = "Regular"

terminal.shell.program = "pwsh"
terminal.shell.args = ["-Login"]

window.dimensions.columns = 128
window.dimensions.lines = 32

window.padding.x = 8
window.padding.y = 8

window.position.x = 30
window.position.y = 30
