cursor.style.shape = "Underline"

font.size = 12.0

font.bold.family = "Maple Mono SC NF"
font.bold.style = "Bold"

font.bold_italic.family = "Maple Mono SC NF"
font.bold_italic.style = "BoldItalic"

font.italic.family = "Maple Mono SC NF"
font.italic.style = "Italic"

font.normal.family = "Maple Mono SC NF"
font.normal.style = "Regular"

shell.program = "pwsh.exe"
shell.args = ["--login"]

window.dimensions.columns = 128
window.dimensions.lines = 32

window.padding.x = 8
window.padding.y = 8

window.position.x = 30
window.position.y = 30
