#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



#
# >>> pcx configuration
#

#
# > bspwm monitor
#
if [[ $(cat /etc/hostname) == '' ]]; then
	:
elif [[ $(cat /etc/hostname) == 'legion7arch' ]]; then

	if [[ 0 == 1 ]]; then
		:

	#>> Double monitor at home
	elif [[ 0 == 1 ]]; then
		bspc monitor HDMI-0 -d [1]EXM
		bspc monitor DP-2 -d [2] [3] [4] [5] [6]
		xrandr \
			--output DP-0 --off \
			--output DP-1 --off \
			--output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal \
			--output DP-2 --mode 1920x1080 --pos 1920x0 --rotate normal

	#>> Single monitor
	elif [[ 0 == 1 ]]; then
		# for NVIDIA
		bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 0
	elif [[ 0 == 1 ]]; then
		# for AMD
		bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

	else
		# Default situation
		bspc monitor -d 1 2 3 4 5 6 7 8 9 0
	fi
elif [[ $(cat /etc/hostname) == 'surfacebook2arch' ]]; then
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
else
	bspc monitor -d A B C D E
fi

#
# > bspwm config
#
bspc config window_gap 8

#
# > Startup
#
pgrep -x picom \
	 > /dev/null || \
	picom &

pgrep -x feh \
	 > /dev/null || \
	feh --bg-fill $HOME/Pictures/SplashScreen.PNG &

pgrep -x fcitx5 \
	 > /dev/null || \
	fcitx5 -d --replace &

#...fcitx5 -d --replace &
#...fcitx5 &

#...pgrep -x ibus \
#...	 > /dev/null || \
#...	ibus-daemon -x -d &

#...ibus-daemon -x -d &
#...ibus &

pgrep -x polybar \
	 > /dev/null || \
	polybar &
#...exec polybar

#
# > Rules
#
function getWidthInPercent {
	echo -n \
	$(( \
		$(xrandr | grep '*' | \
		awk {'print $1'} | \
		awk -F"x" {'print $1'}) *$1 /100 \
	))
}
function getHeightInPercent {
	echo -n \
	$(( \
		$(xrandr | grep '*' | \
		awk {'print $1'} | \
		awk -F"x" {'print $2'}) *$1 /100 \
	))
}
# Anythings
bspc rule --add "*" \
	state=floating \
	center=on \
	#...desktop=any.\!occupied \
	#...follow=on \
	end=line
# kitty
bspc rule --add "kitty" \
	state=tiled \
	end=line
# VLC
bspc rule --add "vlc" \
	state=floating \
	#...state=tiled \
	rectangle=$(getWidthInPercent 75)x$(getHeightInPercent 75)+0+0 \
	center=on \
	end=line
# Microsoft Edge
bspc rule --add "Microsoft-edge" \
	state=tiled \
	end=line
# java: Mindustry
bspc rule --add "java:*:Mindustry" \
	state=fullscreen \
	desktop=any.\!occupied \
	follow=on \
	end=line
bspc rule --add "thunderbird" \
	state=tiled \
	center=on \
	end=line
