#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#>>>bspc monitor -d I II III IV V VI VII VIII IX X
#...bspc monitor -d I II III IV
bspc monitor -d A B C D E

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# pcx configuration
#
bspc config window_gap 8

pgrep -x picom \
	 > /dev/null || \
	picom &

pgrep -x feh \
	 > /dev/null || \
	feh --bg-fill $HOME/Pictures/SplashScreen.PNG

#...pgrep -x polybar \
#...	 > /dev/null || \
#...	polybar
polybar

#...pgrep -x fcitx5 \
#...	 > /dev/null || \
#...	fcitx5 -d --replace &
#...fcitx5 -d --replace &
#...fcitx5 &

#...ibus-daemon -x -d &
#...ibus &
